:: # Copyright 2013, Big Switch Networks, Inc.
:: # Copyright 2018, Red Hat, Inc.
:: #
:: # LoxiGen is licensed under the Eclipse Public License, version 1.0 (EPL), with
:: # the following special exception:
:: #
:: # LOXI Exception
:: #
:: # As a special exception to the terms of the EPL, you may distribute libraries
:: # generated by LoxiGen (LoxiGen Libraries) under the terms of your choice, provided
:: # that copyright and licensing notices generated by LoxiGen are not altered or removed
:: # from the LoxiGen Libraries and the notice provided below is (i) included in
:: # the LoxiGen Libraries, if distributed in source code form and (ii) included in any
:: # documentation for the LoxiGen Libraries, if distributed in binary form.
:: #
:: # Notice: "Copyright 2013, Big Switch Networks, Inc. This library was generated by the LoxiGen Compiler."
:: #
:: # You may not use this file except in compliance with the EPL or LOXI Exception. You may obtain
:: # a copy of the EPL at:
:: #
:: # http://www.eclipse.org/legal/epl-v10.html
:: #
:: # Unless required by applicable law or agreed to in writing, software
:: # distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
:: # WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
:: # EPL for the specific language governing permissions and limitations
:: # under the EPL.
::
:: from loxi_ir import *
:: import go_gen.oftype
:: import go_gen.util as util
:: import loxi_utils.loxi_utils as loxi_utils
::
type ${ofclass.goname} struct {
:: # Embed superclass
:: if ofclass.superclass:
	*${util.go_ident(ofclass.superclass.name)}
:: #endif
::
:: # Create struct properties
:: for member in ofclass.unherited_members:
::     if type(member) != OFPadMember:
::         oftype = go_gen.oftype.get_go_type(member.oftype, version)
::         if not oftype:
::             raise Exception("Could not determine type for %s in %s" % (member.name, ofclass.name))
::         #endif
	${member.goname} ${oftype}
::     #endif
:: #endfor
}
::
:: if ofclass.virtual:

type I${ofclass.goname} interface {
:: if ofclass.superclass:
	I${util.go_ident(ofclass.superclass.name)}
:: else:
	goloxi.Serializable
:: #endif
:: for member in ofclass.unherited_members:
::     if type(member) != OFPadMember:
::         oftype = go_gen.oftype.get_go_type(member.oftype, version)
::         if not oftype:
::             raise Exception("Could not determine type for %s in %s" % (member.name, ofclass.name))
::         #endif
	Get${member.goname}() ${oftype}
::     #endif
:: #endfor
::
:: if ofclass.name == "of_oxm":
	GetValue() interface{}
	GetType() string
:: #endif
}
::
:: for member in ofclass.unherited_members:
::     if type(member) != OFPadMember:
::         oftype = go_gen.oftype.get_go_type(member.oftype, version)
::         if not oftype:
::             raise Exception("Could not determine type for %s in %s" % (member.name, ofclass.name))
::         #endif

func (self *${ofclass.goname}) Get${member.goname}() ${oftype} {
	return self.${member.goname}
}
::     #endif
:: #endfor
::
:: #endif
::
:: base_length = ofclass.embedded_length
:: base_offset = 0
:: for member in ofclass.unherited_members:
::     if type(member) != OFPadMember:
::         base_offset = member.offset
::         break
::     #endif
:: #endfor
::
:: if ofclass.superclass:
::     base_length -= (base_offset if len(ofclass.unherited_members) else ofclass.superclass.embedded_length)
:: #endif
::
:: type_members = [m for m in ofclass.unherited_members if type(m) == OFTypeMember]
::
:: include('_serialize.go', ofclass=ofclass, members=ofclass.unherited_members,
::                          type_members=type_members, base_length=base_length)
::
:: include('_decode.go', ofclass=ofclass, members=ofclass.unherited_members,
::                       base_length=base_length, base_offset=base_offset)
::
:: include('_constructor.go', ofclass=ofclass, type_members=type_members)
::
:: if ofclass.is_oxm and ofclass.name != "of_oxm":
::     include('_oxm.go', ofclass=ofclass)
:: #endif
::
:: if ofclass.is_action and ofclass.name != "of_action":
::     include('_action.go', ofclass=ofclass)
:: #endif