:: # Copyright 2013, Big Switch Networks, Inc.
:: # Copyright 2018, Red Hat, Inc.
:: #
:: # LoxiGen is licensed under the Eclipse Public License, version 1.0 (EPL), with
:: # the following special exception:
:: #
:: # LOXI Exception
:: #
:: # As a special exception to the terms of the EPL, you may distribute libraries
:: # generated by LoxiGen (LoxiGen Libraries) under the terms of your choice, provided
:: # that copyright and licensing notices generated by LoxiGen are not altered or removed
:: # from the LoxiGen Libraries and the notice provided below is (i) included in
:: # the LoxiGen Libraries, if distributed in source code form and (ii) included in any
:: # documentation for the LoxiGen Libraries, if distributed in binary form.
:: #
:: # Notice: "Copyright 2013, Big Switch Networks, Inc. This library was generated by the LoxiGen Compiler."
:: #
:: # You may not use this file except in compliance with the EPL or LOXI Exception. You may obtain
:: # a copy of the EPL at:
:: #
:: # http://www.eclipse.org/legal/epl-v10.html
:: #
:: # Unless required by applicable law or agreed to in writing, software
:: # distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
:: # WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
:: # EPL for the specific language governing permissions and limitations
:: # under the EPL.
::

package goloxi

import (
	"encoding/binary"
)

type Decoder struct {
	buffer []byte
	offset int
	baseOffset int
}

func NewDecoder(data []byte) *Decoder {
	return &Decoder{
		buffer: data,
	}
}

func (d *Decoder) ReadByte() byte {
	c := d.buffer[d.offset]
	d.offset++
	return c
}

func (d *Decoder) ReadUint8() uint8 {
	i := uint8(d.buffer[d.offset])
	d.offset++
	return i
}

func (d *Decoder) ReadUint16() uint16 {
	i := binary.BigEndian.Uint16(d.buffer[d.offset:d.offset+2])
	d.offset += 2
	return i
}

func (d *Decoder) ReadUint32() uint32 {
	i := binary.BigEndian.Uint32(d.buffer[d.offset:d.offset+4])
	d.offset += 4
	return i
}

func (d *Decoder) ReadUint64() uint64 {
	i := binary.BigEndian.Uint64(d.buffer[d.offset:d.offset+8])
	d.offset += 8
	return i
}

func (d *Decoder) ReadUint128() Uint128 {
	hi := binary.BigEndian.Uint64(d.buffer[d.offset:d.offset+8])
	lo := binary.BigEndian.Uint64(d.buffer[d.offset+8:d.offset+16])
	d.offset += 16
	return Uint128{
		Hi: hi,
		Lo: lo,
	}
}

func (d *Decoder) Skip(n int) {
	d.offset += n
}

func (d *Decoder) SkipAlign() {
	d.offset += (d.baseOffset+d.offset+7)/8*8 - d.baseOffset - d.offset
}

func (d *Decoder) Read(n int) []byte {
	data := d.buffer[d.offset:d.offset+n]
	d.offset += n
	return data
}

func (d *Decoder) Length() int {
	return len(d.buffer) - d.offset
}

func (d *Decoder) Bytes() []byte {
	return d.buffer[d.offset:]
}

func (d *Decoder) Offset() int {
	return d.offset
}

func (d *Decoder) BaseOffset() int {
	return d.baseOffset
}

func (d *Decoder) SliceDecoder(length, rewind int) *Decoder {
	newDecoder := NewDecoder(d.buffer[d.offset : d.offset+length-rewind])
	newDecoder.baseOffset = d.offset + d.baseOffset
	d.offset += length - rewind
	return newDecoder
}
